export const MOOD_TAGS_40 = [
  'Sakin',
  'Sosyal',
  'Enerjik',
  'Entelektüel',
  'Yaratıcı',
  'Canlı',
  'Sıcak',
  'Derin',
  'Maceracı',
  'Rahat',
  'Odaklı',
  'Oyuncu',
  'Ruhsal',
  'Kentsel',
  'Açık Hava',
  'Mahrem',
  'Açık',
  'Niş',
  'Yeni Başlayan Dostu',
  'Uzman',
  'Motive Edici',
  'Felsefi',
  'Yansıtıcı',
  'Hızlı Tempolu',
  'Yavaş Tempolu',
  'Gece Geç',
  'Sabah',
  'Hafta Sonu Rituali',
  'Yağmurlu Gün',
  'Güneşli',
  'Rekabetçi',
  'İş Birlikçi',
  'Sessiz',
  'Gürültülü ve Eğlenceli',
  'Bilinçli',
  'Keşif',
  'Nostaljik',
  'Deneysel',
  'Yapılandırılmış',
  'Serbest',
];
